import "../styles/globals.scss";
import { ChakraProvider } from "../providers/chakra.provider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="p-0 m-0 bg-[color:var(--bg-grey-1)]">
				<ChakraProvider>{children}</ChakraProvider>
			</body>
		</html>
	);
}
